// auth services
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const LIST_ROLES_SUCCESS = "LIST_ROLES_SUCCESS";
export const LIST_ROLES_FAIL = "LIST_ROLES_FAIL";

// user services

export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// product services
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const LIST_PRODUCTS_SUCCESS = "LIST_PRODUCTS_SUCCESS"
export const LIST_PRODUCTS_FAIL = "LIST_PRODUCTS_FAIL"


// Order services action types
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";

export const LIST_ORDERS_SUCCESS = "LIST_ORDERS_SUCCESS";
export const LIST_ORDERS_FAIL = "LIST_ORDERS_FAIL";

export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const UPDATE_ORDER_MACHINE_ID_SUCCESS = "UPDATE_ORDER_MACHINE_ID_SUCCESS";
export const UPDATE_ORDER_MACHINE_ID_FAIL = "UPDATE_ORDER_MACHINE_ID_FAIL";

export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";

export const UPDATE_ORDER_QUALITY_SUCCESS = "UPDATE_ORDER_QUALITY_SUCCESS";
export const UPDATE_ORDER_QUALITY_FAIL = "UPDATE_ORDER_QUALITY_FAIL";

export const UPDATE_ORDER_PACKAGING_SUCCESS = "UPDATE_ORDER_PACKAGING_SUCCESS";
export const UPDATE_ORDER_PACKAGING_FAIL = "UPDATE_ORDER_PACKAGING_FAIL";
  
export const UPDATE_ORDER_FEEDBACK_SUCCESS = "UPDATE_ORDER_FEEDBACK_SUCCESS";
export const UPDATE_ORDER_FEEDBACK_FAIL = "UPDATE_ORDER_FEEDBACK_FAIL";

export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
  
